import { scenarios, signalMeta, liveChat } from './data.js';
import { scoreMessage, riskLevel } from './riskEngine.js';

const app = document.querySelector('#app');
const state = { entered: false, page: 'chat', mode: 'live', scenario: 'gradual', index: 0, chatIndex: 0, messages: [], score: 0, seen: [], history: [], playing: false, typing: false, alert: false, reviewTab: 'signals', timer: null, responseTimer: null, settings: { alerts: true, analysis: true, notifications: true, demo: true } };
const icons = { chats:'◌', safety:'◈', demo:'▷', settings:'⚙', privacy:'⌾', trajectory:'⌁', verify:'✓' };

function levelClass(score=state.score) { return riskLevel(score).toLowerCase().replace(' ', '-'); }
function resetScenario(key=state.scenario) { state.mode='demo'; state.scenario=key; state.index=0; state.messages=[]; state.score=0; state.seen=[]; state.history=[]; state.playing=false; state.typing=false; state.alert=false; clearInterval(state.timer); clearTimeout(state.responseTimer); render(); }
function escapeHTML(value) { return value.replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]); }
function addChatMessage(sender, text) {
  const result=scoreMessage(text,state,sender);
  state.score=result.score; state.seen=result.seen;
  const now = new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
  state.messages.push({id:`chat-${state.messages.length}`,sender,text,time:now,signals:result.signals,contribution:result.contribution,previous:result.previous,score:result.score});
  if(result.contribution || state.messages.length===1) state.history.push({label: result.signals[0] || 'Conversation', score: result.score, previous: result.previous, time: now});
  if(state.score>=70 && !state.alert && state.settings.alerts) state.alert=true;
}
function startLiveChat() {
  state.mode='live'; state.chatIndex=0; state.index=0; state.messages=[]; state.score=0; state.seen=[]; state.history=[]; state.playing=false; state.typing=false; state.alert=false;
  clearInterval(state.timer); clearTimeout(state.responseTimer);
  const opening=liveChat[state.chatIndex++]; addChatMessage('alex', opening.text); render();
}
function sendUserMessage(value) {
  const text=value.trim(); if(!text || state.typing) return;
  if(state.mode!=='live') startLiveChat();
  addChatMessage('you', text); state.typing=true; render();
  state.responseTimer=setTimeout(() => {
    state.typing=false;
    const reply=liveChat[state.chatIndex++];
    if(reply) addChatMessage('alex', reply.text);
    render();
  }, 650);
}
function advance() {
  const entries=scenarios[state.scenario].messages;
  if(state.index>=entries.length){ stop(); return; }
  const [sender,text]=entries[state.index];
  const result=scoreMessage(text,state,sender);
  state.score=result.score; state.seen=result.seen;
  const now = new Date(Date.now()+state.index*60000).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
  state.messages.push({id:state.index,sender,text,time:now,signals:result.signals,contribution:result.contribution,previous:result.previous,score:result.score});
  if(result.contribution || state.index===0) state.history.push({label: result.signals[0] || 'Conversation', score: result.score, previous: result.previous, time: now});
  state.index++;
  if(state.score>=70 && !state.alert && state.settings.alerts){ state.alert=true; }
  render();
}
function play(){ if(state.index>=scenarios[state.scenario].messages.length) resetScenario(); state.playing=true; state.timer=setInterval(advance,1150); advance(); render(); }
function stop(){ state.playing=false; clearInterval(state.timer); render(); }
function nav(page){ state.page=page; state.alert=false; render(); }

function brand(){ return `<div class="brand"><span class="shield">⌬</span><span>AUREX</span></div>`; }
function riskBadge(compact=false){ const level=riskLevel(); return `<button class="risk-bubble ${levelClass()} ${compact?'compact':''}" data-action="review" aria-label="Open AUREX Safety Review"><span class="bubble-icon">${level==='HIGH RISK'?'!':'⌬'}</span><span><b>AUREX</b><em>${level}</em></span><strong>${state.score}</strong></button>`; }
function sidebar(){ const items=[['chat','chats','Chats'],['safety','safety','Safety Review'],['insight','safety','Safety Insight'],['trajectory','trajectory','Trajectory'],['demo','demo','Demo Scenarios'],['privacy','privacy','Privacy'],['settings','settings','Settings']]; return `<aside class="sidebar"><div>${brand()}<p class="product-label">Conversation Protection</p></div><nav>${items.map(([p,i,label])=>`<button class="nav-item ${state.page===p?'selected':''}" data-page="${p}"><i>${icons[i]}</i>${label}</button>`).join('')}</nav><div class="active-status"><span></span><div><b>Protection active</b><small>Local demo analysis</small></div></div></aside>`; }
function shell(content){ return `<div class="shell">${sidebar()}<main class="main"><header class="topbar"><button class="mobile-brand" data-page="chat">${brand()}</button><div class="top-title">${state.page==='chat'?'Conversation': state.page==='safety'?'Safety intelligence':''}</div><button class="profile" data-page="settings"><span>NA</span><b>Profile</b> ⚙</button></header>${content}</main></div>${state.page==='chat'?riskBadge():''}${state.alert?alertModal():''}`; }
function welcome(){ return `<section class="welcome"><div class="welcome-panel"><div class="welcome-nav">${brand()}<span>Privacy-first • Demo ready</span></div><div class="hero-copy"><span class="eyebrow">CONVERSATION SAFETY, REIMAGINED</span><h1>Your Conversation<br/><i>Safety Layer.</i></h1><p>Detect escalating patterns. Understand why they matter. Pause before risk becomes harm.</p><div class="hero-actions"><button class="primary" data-action="enter">Get Started <b>→</b></button><span>Built to analyze behavior,<br/>not identity.</span></div><div class="feature-row"><div>✦<b>AI-Powered</b><small>Analysis</small></div><div>⌁<b>Behavioral Pattern</b><small>Detection</small></div><div>⌬<b>Privacy</b><small>Focused</small></div></div></div><div class="hero-visual"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="phone"><div class="phone-top"><span>9:41</span><b>⌬ AUREX</b><span>● ●</span></div><div class="contact"><span class="avatar">A</span><div><b>Alex</b><small>● Online</small></div></div><div class="mini-msg them">I feel like you really understand me.</div><div class="mini-msg yours">I'm glad you feel heard.</div><div class="mini-msg them alert-msg">Don't tell anyone about us.<small>⌬ Secrecy detected</small></div><div class="mini-risk"><span>⌬</span><div><b>AUREX</b><small>Watching for patterns</small></div><em>24</em></div></div><div class="hero-shield">⌬<small>Protection<br/>in context</small></div></div></div><p class="philosophy">“AUREX doesn't judge a person. It analyzes the conversation's trajectory.”</p></section>`; }
function chat(){
  const nextReply=state.mode==='live' ? liveChat[state.chatIndex] : null;
  const helper=nextReply ? `<div class="reply-helper"><span>Suggested reply</span><button data-action="use-suggestion">${escapeHTML(nextReply.suggestion)}</button></div>` : state.mode==='live' ? `<div class="reply-helper complete"><span>Conversation complete</span><button data-action="restart-live">Start again</button></div>` : '';
  const typing=state.typing ? `<div class="typing"><span></span><span></span><span></span> Alex is typing</div>` : '';
  return shell(`<section class="chat-page"><div class="chat-column"><div class="chat-head"><button class="back" aria-label="Back">‹</button><span class="avatar">A</span><div><h2>Alex</h2><p><span class="online"></span> Online</p></div><div class="chat-tools">⌕ <button aria-label="More options">•••</button></div></div><div class="chat-notice"><span>⌬</span><span><b>AUREX is watching for patterns</b><small>Analysis stays focused on conversation behavior, not identity.</small></span><button data-page="privacy">Learn more</button></div><div class="message-list">${state.messages.map(message).join('')}${typing}<div id="bottom"></div></div>${helper}<div class="composer"><button aria-label="Attach">＋</button><input id="message-input" placeholder="Message Alex…" aria-label="Message Alex" ${state.typing?'disabled':''}/><button class="send" data-action="send-message" aria-label="Send message" ${state.typing?'disabled':''}>↑</button></div></div><aside class="chat-aside"><div class="aside-hero"><span class="mini-shield">⌬</span><p>Conversation Status</p><h3 class="${levelClass()}">${riskLevel()}</h3><div class="score-line"><b>${state.score}</b><span>/ 100</span></div><div class="meter"><i style="width:${state.score}%"></i></div><p class="status-copy">${state.score<25?'No meaningful harmful pattern detected yet.':state.score<70?'Patterns are accumulating. Consider pausing before sharing sensitive things.':'Multiple signals have intensified. Pause and verify before sending money or private content.'}</p><button class="text-btn" data-action="review">Open safety review →</button></div>${controlPanel()}<div class="trajectory-mini"><div><b>Risk trajectory</b><button data-page="trajectory">View</button></div>${miniChart()}</div></aside></section>`);
}
function message(m){ return `<div class="message-row ${m.sender==='you'?'mine':''}"><div class="message ${m.sender==='you'?'out':'in'}">${escapeHTML(m.text)}<small>${m.time}</small></div>${m.signals.length?`<div class="analysis"><span>⌬</span><b>AUREX</b><em>${m.signals.map(s=>signalMeta[s][1]).join(' + ')}${m.contribution?` <strong>+${m.contribution}</strong>`:''}</em></div>`:''}</div>`; }
function controlPanel(){
  if(state.mode==='live') return `<div class="control-panel live-control"><div class="control-header"><span>GUIDED CHAT</span><b>Alex responds as you message</b></div><p>Reply naturally, or use the suggested response below. The conversation gradually changes over time.</p><button class="secondary small live-reset" data-action="restart-live">↻ Restart conversation</button><button class="text-btn demo-switch" data-action="open-demo">Use a demo scenario →</button><div class="control-progress"><span>Alex replies: <b>${state.chatIndex} / ${liveChat.length}</b></span><span>Risk: <b>${state.score} / 100</b></span></div></div>`;
  const total=scenarios[state.scenario].messages.length;
  return `<div class="control-panel"><div class="control-header"><span>LIVE DEMO</span><b>${scenarios[state.scenario].title}</b></div><div class="select-row"><select data-action="scenario" aria-label="Demo scenario">${Object.entries(scenarios).map(([key,item])=>`<option value="${key}" ${key===state.scenario?'selected':''}>${item.title}</option>`).join('')}</select></div><div class="controls"><button data-action="play" ${state.playing?'disabled':''}>▶ Play</button><button data-action="pause" ${!state.playing?'disabled':''}>Ⅱ Pause</button><button data-action="next">⏭ Next</button><button data-action="reset">↻</button></div><div class="control-progress"><span>Message: <b>${state.index} / ${total}</b></span><span>Risk: <b>${state.score} / 100</b></span></div></div>`;
}
function miniChart(){ const points=state.history.length?state.history:[{score:0}]; return `<svg viewBox="0 0 300 94" preserveAspectRatio="none" aria-label="Conversation risk trajectory"><path d="M0,86 H300" class="grid"/><polyline points="${points.map((h,i)=>`${i/(Math.max(1,points.length-1))*290+5},${87-h.score*.72}`).join(' ')}"/><g>${points.map((h,i)=>`<circle cx="${i/(Math.max(1,points.length-1))*290+5}" cy="${87-h.score*.72}" r="3"/>`).join('')}</g></svg>`; }
function alertModal(){ return `<div class="modal-backdrop"><div class="safety-alert"><div class="alert-icon">!</div><span class="eyebrow coral">AUREX SAFETY ALERT</span><h2>This conversation is showing an escalating pattern.</h2><p>Multiple signals have intensified over time. Pause and verify before sending money or private content.</p><div class="alert-score"><b>${state.score}</b><span>/100<br/><em>HIGH RISK</em></span></div><div class="alert-buttons"><button class="primary" data-action="review">Review safety signals</button><button class="secondary" data-action="dismiss">Not now</button></div></div></div>`; }
function safety(){ const level=riskLevel(); const cards=state.seen.length?state.seen:['emotional_dependency','secrecy','emotional_pressure','urgency','financial_request']; return shell(`<section class="page safety-page"><div class="page-heading"><span class="eyebrow">AUREX INTELLIGENCE</span><h1>AUREX Safety Review</h1><p>Clear, explainable context for what is happening in this conversation.</p></div><div class="safety-grid"><div class="risk-card"><div class="ring ${levelClass()}" style="--score:${state.score}"><div><b>${state.score}</b><small>/ 100</small></div></div><h2 class="${levelClass()}">${level}</h2><p>Conversation Risk</p><button class="primary small" data-page="verify">Verify before trusting →</button></div><div class="explanation-card"><span class="section-kicker">WHY YOU'RE SEEING THIS</span><h2>Patterns matter more than one message.</h2><p>${state.score<25?'AUREX has not found a meaningful escalation pattern. It will remain available as the conversation develops.':'Multiple behavioral signals have appeared and intensified through this conversation. AUREX detected a progression toward pressure and requests, which can make it harder to pause and assess safely.'}</p><div class="pattern-flow"><span>Trust</span><i>→</i><span>Dependency</span><i>→</i><span>Pressure</span><i>→</i><span>Requests</span></div></div></div><div class="review-tabs"><button class="${state.reviewTab==='signals'?'active':''}" data-tab="signals">Detected signals</button><button class="${state.reviewTab==='actions'?'active':''}" data-tab="actions">Recommended action</button><button class="${state.reviewTab==='history'?'active':''}" data-tab="history">Risk history</button></div>${reviewContent(cards)}</section>`); }
function insight(){ const featured=state.seen.length?state.seen:['emotional_dependency','secrecy','emotional_pressure','urgency','financial_request','private_content_request']; return shell(`<section class="page insight-page"><div class="insight-hero"><span class="eyebrow">AUREX SAFETY INSIGHT</span><h1>${state.score>=45?'This conversation is showing potentially harmful escalation.':'AUREX is keeping an eye on the conversation.'}</h1><p>${state.score>=45?'Please pause and verify before sending money or private content.':'No strong escalation pattern has appeared yet. AUREX will continue to look for changes over time.'}</p><button class="primary" data-page="safety">Open full review →</button></div><div class="insight-columns"><section><h2>Detected Signals</h2>${featured.slice(0,6).map(s=>`<div class="insight-signal"><span>${signalMeta[s][0]}</span><b>${signalMeta[s][1]}</b><small>Observed in the conversation</small></div>`).join('')}</section><section><h2>Safety Tips</h2><div class="tip"><b>Pause before responding</b><p>Pressure works best when you are rushed. Take time to assess.</p></div><div class="tip"><b>Protect money and private content</b><p>Do not share either while uncertainty or pressure is present.</p></div><div class="tip"><b>Use an independent check</b><p>Verify through a trusted channel you control.</p></div><button class="secondary small" data-page="verify">View verification guidance</button></section></div><div class="insight-privacy">⌬ <b>Your privacy matters.</b> AUREX analyzes conversation patterns, not personal identity. It does not label people as scammers.</div></section>`); }
function reviewContent(cards){ if(state.reviewTab==='actions') return `<div class="action-grid"><article><span>Ⅱ</span><h3>Pause before responding</h3><p>Give yourself space before responding to a request that feels pressuring.</p></article><article><span>₹</span><h3>Don't send money</h3><p>Do not make financial transfers while an escalating pattern is present.</p></article><article><span>▣</span><h3>Don't send private content</h3><p>Keep personal images and information private until you feel safe.</p></article><article><span>◎</span><h3>Verify independently</h3><p>Use a trusted channel or trusted mutual contact before sharing.</p></article><div class="wide-action"><button class="primary" data-page="verify">Continue safely: see verification options →</button></div></div>`; if(state.reviewTab==='history') return `<div class="risk-history">${state.history.length?state.history.map(h=>`<div><span>${h.time}</span><i></i><p><b>Risk ${h.previous} → ${h.score}</b><small>${signalMeta[h.label]?.[1] || h.label} detected</small></p></div>`).join(''):`<div class="history-empty">Play a scenario to generate an explainable risk audit trail.</div>`}</div>`; return `<div class="signal-grid">${cards.map(s=>{const [icon,name,weight,copy]=signalMeta[s]; return `<article class="signal-card"><span>${icon}</span><div><h3>${name}</h3><p>${copy}</p></div><b>+${weight}</b></article>`}).join('')}</div>`; }
function trajectory(){ const pts=state.history.length?state.history:[{score:0,label:'Start'}]; return shell(`<section class="page trajectory-page"><div class="page-heading"><span class="eyebrow">EXPLAINABLE RISK ENGINE</span><h1>Conversation Trajectory</h1><p>AUREX detects the trajectory, not just a single suspicious message.</p></div><div class="big-chart"><div class="chart-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><svg viewBox="0 0 760 300" preserveAspectRatio="none"><g class="chart-grid"><path d="M0 0H760 M0 75H760 M0 150H760 M0 225H760 M0 300H760"/></g><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#6d5efc" stop-opacity=".25"/><stop offset="1" stop-color="#6d5efc" stop-opacity="0"/></linearGradient></defs><path class="area" d="M${pts.map((h,i)=>`${i/(Math.max(1,pts.length-1))*730+15} ${285-h.score*2.65}`).join(' L')} L745 300 L15 300 Z"/><polyline points="${pts.map((h,i)=>`${i/(Math.max(1,pts.length-1))*730+15},${285-h.score*2.65}`).join(' ')}"/>${pts.map((h,i)=>`<g class="chart-dot"><circle cx="${i/(Math.max(1,pts.length-1))*730+15}" cy="${285-h.score*2.65}" r="6"/><text x="${i/(Math.max(1,pts.length-1))*730+15}" y="${270-h.score*2.65}">${h.score}</text></g>`).join('')}</svg></div><div class="chart-names">${pts.map(h=>`<span>${signalMeta[h.label]?.[1] || h.label}</span>`).join('')}</div><div class="trajectory-explain"><div><span>RISK PROGRESSION</span><h2>Signals gain meaning in sequence.</h2><p>Each point reflects the conversation history to that moment, including escalation bonuses when signals appear in a concerning pattern.</p></div><div class="progression-chain"><b>Trust</b><i>↓</i><b>Dependency</b><i>↓</i><b>Secrecy</b><i>↓</i><b>Pressure</b><i>↓</i><b>Request</b></div></div></section>`); }
function demo(){ return shell(`<section class="page demo-page"><div class="page-heading"><span class="eyebrow">PRESENTATION MODE</span><h1>Demo Scenarios</h1><p>Show how AUREX responds differently to normal conversation, gradual escalation, and concentrated high-risk patterns.</p></div><div class="scenario-cards">${Object.entries(scenarios).map(([key,s],i)=>`<article class="scenario ${key===state.scenario?'chosen':''}"><div class="scenario-num">0${i+1}</div><span class="scenario-risk ${key}">${key==='normal'?'SAFE 0–24':key==='gradual'?'ESCALATING':'HIGH RISK'}</span><h2>${s.title}</h2><p>${s.subtitle}</p><div class="scenario-foot"><span>${s.messages.length} messages</span><div><button class="secondary small" data-action="select" data-scenario="${key}">Preview</button><button class="primary small" data-action="start" data-scenario="${key}">Play scenario</button></div></div></article>`).join('')}</div><div class="demo-bottom"><div><span>⌬</span><p><b>A quick judge-ready flow</b><small>Pick a scenario, play live messages, and open Safety Review as signals accumulate.</small></p></div><button class="primary" data-action="start" data-scenario="gradual">Start Gradual Escalation →</button></div></section>`); }
function verify(){ return shell(`<section class="page verify-page"><div class="verify-hero"><span class="verify-icon">✓</span><span class="eyebrow">SAFETY GUIDANCE</span><h1>Verify Before You Trust</h1><p>AUREX cannot verify someone's identity for you. Consider confirming the person through a trusted channel before sharing money or private content.</p></div><div class="verify-options"><article><span>▣</span><h2>Video call</h2><p>Confirm the person through a live video interaction using a channel you choose.</p></article><article><span>◎</span><h2>Known social profile</h2><p>Compare with an established profile you already trust — AUREX does not scrape profiles.</p></article><article><span>♧</span><h2>Trusted mutual contact</h2><p>Ask someone you already know if they can independently confirm the person.</p></article></div><div class="guidance-note"><b>Remember:</b> Verification is a personal safety step, not an accusation. You decide what to do next.</div><button class="secondary" data-page="safety">← Back to safety review</button></section>`); }
function privacy(){ return shell(`<section class="page privacy-page"><div class="page-heading"><span class="eyebrow">PRIVACY BY DESIGN</span><h1>Safety without identity profiling.</h1><p>AUREX focuses on interaction patterns and keeps the user in control.</p></div><div class="privacy-grid">${[['⌁','Conversation-level analysis','AUREX considers the pattern across messages, not who the person is.'],['◉','No identity profiling','The MVP does not investigate, identify, or score the person behind a chat.'],['!','No “scammer” labeling','AUREX reports conversation risk, never a claim of criminality.'],['◷','Minimal data retention','Only the information needed for this local demo is kept.'],['⌬','User-controlled alerts','Safety guidance supports your choice; it never acts on your behalf.']].map(([i,h,p])=>`<article><span>${i}</span><h2>${h}</h2><p>${p}</p></article>`).join('')}</div><div class="privacy-architecture"><b>Message</b><i>→</i><b>Local signal detection</b><i>→</i><b>Trajectory score</b><i>→</i><b>Safety guidance</b><small>Identity and criminality are outside AUREX's scope.</small></div></section>`); }
function settings(){ return shell(`<section class="page settings-page"><div class="page-heading"><span class="eyebrow">PREFERENCES</span><h1>Settings</h1><p>Fine-tune how AUREX supports your conversation safety.</p></div><div class="settings-card"><h2>Profile</h2><div class="profile-row"><span class="profile-big">NA</span><div><b>Safety-aware user</b><small>Demo profile · Local workspace</small></div><button class="secondary small">Edit</button></div></div><div class="settings-card"><h2>AUREX Preferences</h2>${[['alerts','Safety Alerts','Show a gentle device-style alert when risk reaches high.'],['analysis','Message Analysis','Analyze new messages for behavioral signals.'],['notifications','Risk Notifications','Show status changes as conversation risk evolves.'],['demo','Demo Mode','Keep local scenarios ready for presentation.']].map(([key,h,p])=>`<label class="toggle-row"><div><b>${h}</b><small>${p}</small></div><input type="checkbox" data-setting="${key}" ${state.settings[key]?'checked':''}/><span class="toggle"></span></label>`).join('')}</div><div class="settings-links"><button data-page="privacy">Privacy & Security <span>›</span></button><button data-page="verify">Help & Support <span>›</span></button></div></section>`); }
function render(){ app.innerHTML=state.entered?({chat,safety,insight,trajectory,demo,privacy,settings,verify}[state.page]||chat)():welcome(); bind(); if(state.entered && state.page==='chat') requestAnimationFrame(()=>document.querySelector('#bottom')?.scrollIntoView({block:'end'})); }
function bind(){
  document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
  document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.reviewTab=b.dataset.tab;render()}));
  document.querySelectorAll('[data-setting]').forEach(i=>i.addEventListener('change',()=>{state.settings[i.dataset.setting]=i.checked;}));
  document.querySelectorAll('select[data-action="scenario"]').forEach(select=>select.addEventListener('change',()=>resetScenario(select.value)));
  const input=document.querySelector('#message-input');
  if(input) input.addEventListener('keydown', event=>{ if(event.key==='Enter'){ event.preventDefault(); sendUserMessage(input.value); } });
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{
    const a=b.dataset.action;
    if(a==='enter'){ state.entered=true; startLiveChat(); }
    if(a==='play')play(); if(a==='pause')stop(); if(a==='next')advance(); if(a==='reset')resetScenario();
    if(a==='review')nav('safety'); if(a==='dismiss'){state.alert=false;render()}
    if(a==='select'){resetScenario(b.dataset.scenario);nav('chat')}
    if(a==='start'){resetScenario(b.dataset.scenario);nav('chat');setTimeout(play,150);}
    if(a==='restart-live')startLiveChat(); if(a==='open-demo')nav('demo');
    if(a==='use-suggestion'){ const composer=document.querySelector('#message-input'); if(composer){ composer.value=liveChat[state.chatIndex]?.suggestion||''; composer.focus(); } }
    if(a==='send-message')sendUserMessage(document.querySelector('#message-input')?.value||'');
  }));
}
render();
